### ISSUE TITLE
Request: lower minimum brightness

### ISSUE THREAD

**Issue by jrenner** [johnnyslt/android#10]
NOTE: this is still as of the CM 10.1 build, not sure if this has changed.

I find the minimum brightness to be a little too bright for my purposes.  Is it possible to have a lower minimum brightness? (It was lower when I was using the stock HTC Evo 3D Android 4.0.3)

**Comment by jrenner** [comment]
I take that as a no? :)

**Comment by johnnyslt** [comment]
Did you checked it in CM 11 ?
