### ISSUE TITLE
...

### ISSUE THREAD

**Issue by ghost** [johnnyslt/android#16]

**Comment by johnnyslt** [comment]
Please try this kernel and see if its more stable: https://dl.dropboxusercontent.com/u/11729627/shooteru-kernel-06-01-2014-1220.zip

I've increased ION memory.

**Comment by johnnyslt** [comment]
Please post a other last_kmsg after the phone reboots with the above Kernel.

**Comment by johnnyslt** [comment]
I've increased ION memory a bit more since then.

I'm seeing a lot of errors in your logcat, did you tried to wipe cache+dalvik and fix permissions?  How are you restoring your apps? What recovery are you using?
