### ISSUE TITLE
cLock alarm

### ISSUE THREAD

**Issue by charles1510** [johnnyslt/android#20]
I've noticed that if I have 2 alarms set one after another and i won't do anything when the first rang and second start my cpu doing 100%, phone is getting really hot and not ringing anymore (sometimes).

<a href="http://www.youtube.com/watch?feature=player_embedded&v=qDu9m4IaAlk
" target="_blank"><img src="http://img.youtube.com/vi/qDu9m4IaAlk/0.jpg" 
 </a>

LOGCAT:
https://drive.google.com/file/d/0B60RFU8et9Rzb3BTTW1XTEVlMk0/edit?usp=sharing

DMESG:
https://drive.google.com/file/d/0B60RFU8et9RzeTBIc3BKQW1rQkE/edit?usp=sharing

KMSG:
https://drive.google.com/file/d/0B60RFU8et9RzZ0tLNjhPYjA4QW8/edit?usp=sharing

**Comment by johnnyslt** [comment]
Fixed in next version.
