### ISSUE TITLE
Wifi search refresh rate problem

### ISSUE THREAD

**Issue by lpla** [johnnyslt/android#22]
(I also reported this in the forum)

After 45 minutes approximately after being disconnected from an access point, the ROM stops searching access points until I open the wifi settings view or I disconnect and reconnect wifi (thought "Settings" or quick settings). I had this issue since CM 10.2. Anyone who suffer also this? Is there any way to debug or obtain a log of this?

**Comment by johnnyslt** [comment]
The wifi bug is more like Google problem. Some nexus suffer from it also. 

Disable Optimize Wi-Fi from Wi-Fi advanced settings and it should happen less often.
