### ISSUE TITLE
Google play music hiccups

### ISSUE THREAD

**Issue by lordvlad** [johnnyslt/android#4]
When listening to music (latest Google play music from Google play) with the screen off, I get occasional hiccups. In the cm10.2 version from 1609 as well as the one before. When the screen is on, there are no hiccups. Whether the music is streaming or playing off the SD card doesn't matter.

**Comment by jrenner** [comment]
I have this too

**Comment by johnnyslt** [comment]
It will be fixed in next version. I'm changing kernel to mrg666's.

**Comment by lordvlad** [comment]
still experiencing hiccups. your cm10.2 20.09, mrg666's kernel 21.09.

**Comment by johnnyslt** [comment]
Streaming or from sdcard?

**Comment by lordvlad** [comment]
Both.
Min CPU is 348. Will try with 432.
Am 23.09.2013 18:08 schrieb "Dărescu Ionuț" notifications@github.com:

**Comment by lordvlad** [comment]
still there with min CPU at 432.
as i said before, when the screen is on, no hiccups, even with heavy games.

**Comment by johnnyslt** [comment]
Can you try deleting power.msm8660.so from system/lib/hw, and see if the hiccups still occur ?

**Comment by johnnyslt** [comment]
Fixed in next version !
