### ISSUE TITLE
google maps glitches

### ISSUE THREAD

**Issue by lordvlad** [johnnyslt/android#5]
Sometimes, google maps starts to make freaky glitches, even when i'm not touching the screen. When i kill it (long press back button) and start it again, the glitches are gone for a while. when i'm using gmaps again for about 5min+, the glitching starts again. This happend on an Motorola Defy (CM10.1) of mine, too, so its may be rather a CM/Gmaps bug, but I thought I'll post it anyway, since it looks so empty here :D I'll post a log next time I encounter these glitches.

**Comment by jrenner** [comment]
I also have this. HTC evo 3d cm 10.1

**Comment by lordvlad** [comment]
Seems to be gone on 2009 with Mirage kernel 2109

**Comment by johnnyslt** [comment]
Temp fix: Enable > Settings > Dev. Options > Force MSAA 4x

**Comment by Gretschy** [comment]
Hi, for me the Temp fix doesn't work. Whenever I pull down the status bar while navigating, the screen begins to flash and the navigation is very inacurate.
I am on the latest (29.9.) build. Thank you very much for your hard work.

**Comment by vidplace7** [comment]
Here's a link to the latest version that doesn't glitch out :) working great for me on 4.3.1
https://dl.dropboxusercontent.com/u/8701440/old.google.maps.apk
