### ISSUE TITLE
blank screen in PewPew (game)

### ISSUE THREAD

**Issue by lordvlad** [johnnyslt/android#7]
I played this game a lot on my motorola defy (cm 10.1), but on the evo (cm 10.2) i can't get it to work. i tried several dev options, but i only get a black screen. all other games have no problems at all.

this is the game:
https://play.google.com/store/apps/details?id=com.jyaif.pewpew

**Comment by johnnyslt** [comment]
I'm not seeing any errors when I start the game. 

Probably its not compatible with our phone.

Did it worked on SENSE?

**Comment by lordvlad** [comment]
never tried it on sense, i CM'ed the phone as soon as i got it.

**Comment by johnnyslt** [comment]
Fixed !
